import 'package:flutter/material.dart';

void main() => runApp(const Reserva7App());

class Reserva7App extends StatelessWidget {
  const Reserva7App({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    debugShowCheckedModeBanner: false,
    title: 'Reserva7',
    theme: ThemeData(useMaterial3: true, colorSchemeSeed: const Color(0xFF0D3B36), scaffoldBackgroundColor: const Color(0xFFF7F7F3), fontFamily: 'Arial'),
    home: const SplashPage(),
  );
}

class SplashPage extends StatefulWidget { const SplashPage({super.key}); @override State<SplashPage> createState()=>_SplashPageState(); }
class _SplashPageState extends State<SplashPage> {
  @override void initState(){super.initState(); Future.delayed(const Duration(seconds:2),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const OnboardingPage()));});}
  @override Widget build(BuildContext context)=>const Scaffold(body: Center(child: Column(mainAxisSize: MainAxisSize.min,children:[Icon(Icons.restaurant_rounded,size:64,color:Color(0xFF0D3B36)),SizedBox(height:18),Text('RESERVA7',style:TextStyle(fontSize:30,fontWeight:FontWeight.w800,letterSpacing:5)),SizedBox(height:8),Text('Reserve. Experience. Enjoy.',style:TextStyle(color:Colors.black54))])));
}

class OnboardingPage extends StatefulWidget { const OnboardingPage({super.key}); @override State<OnboardingPage> createState()=>_OnboardingPageState(); }
class _OnboardingPageState extends State<OnboardingPage>{ int page=0; final data=[('Descubra lugares especiais','Encontre restaurantes, experiências e mesas que combinam com você.',Icons.explore_rounded),('Reserve em poucos segundos','Veja horários disponíveis e confirme sua mesa sem complicação.',Icons.event_available_rounded),('Tenha tudo em um só lugar','Acompanhe suas reservas e descubra novas experiências.',Icons.auto_awesome_rounded)];
Widget build(BuildContext c){final d=data[page];return Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(28),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const Spacer(),Container(height:300,decoration:BoxDecoration(color:Color(0xFFE3EAE5),borderRadius:BorderRadius.all(Radius.circular(32))),child:Center(child:Icon(Icons.restaurant_menu_rounded,size:110,color:Color(0xFF0D3B36)))),const SizedBox(height:42),Text(d.$1,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800)),const SizedBox(height:14),Text(d.$2,style:const TextStyle(fontSize:17,color:Colors.black54,height:1.45)),const Spacer(),Row(mainAxisAlignment:MainAxisAlignment.center,children:List.generate(3,(i)=>AnimatedContainer(duration:const Duration(milliseconds:200),margin:const EdgeInsets.all(4),width:i==page?28:8,height:8,decoration:BoxDecoration(color:i==page?const Color(0xFF0D3B36):Colors.black12,borderRadius:BorderRadius.circular(8))))),const SizedBox(height:22),FilledButton(onPressed:(){if(page<2)setState(()=>page++);else Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const LoginPage()));},style:FilledButton.styleFrom(padding:const EdgeInsets.all(17)),child:Text(page<2?'Continuar':'Começar')),const SizedBox(height:10),if(page<2)TextButton(onPressed:()=>Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const LoginPage())),child:const Text('Pular'))]))));}}

class LoginPage extends StatelessWidget { const LoginPage({super.key}); @override Widget build(BuildContext c)=>AuthShell(title:'Bem-vindo de volta',subtitle:'Entre para continuar sua experiência.',children:[const Field(label:'E-mail',icon:Icons.email_outlined),const SizedBox(height:14),const Field(label:'Senha',icon:Icons.lock_outline,obscure:true),Align(alignment:Alignment.centerRight,child:TextButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const RecoveryPage())),child:const Text('Esqueci minha senha'))),const SizedBox(height:8),FilledButton(onPressed:()=>Navigator.pushReplacement(c,MaterialPageRoute(builder:(_)=>const HomePage())),child:const Text('Entrar')),const SizedBox(height:18),OutlinedButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const RegisterPage())),child:const Text('Criar minha conta'))]); }

class RegisterPage extends StatelessWidget { const RegisterPage({super.key}); @override Widget build(BuildContext c)=>AuthShell(title:'Crie sua conta',subtitle:'Leva menos de um minuto.',children:[const Field(label:'Nome completo',icon:Icons.person_outline),const SizedBox(height:14),const Field(label:'E-mail',icon:Icons.email_outlined),const SizedBox(height:14),const Field(label:'Telefone',icon:Icons.phone_outlined),const SizedBox(height:14),const Field(label:'Senha',icon:Icons.lock_outline,obscure:true),const SizedBox(height:24),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const VerifyPage())),child:const Text('Continuar'))]); }

class RecoveryPage extends StatelessWidget { const RecoveryPage({super.key}); @override Widget build(BuildContext c)=>AuthShell(title:'Recuperar acesso',subtitle:'Informe seu e-mail e enviaremos um código de verificação.',children:[const Field(label:'E-mail',icon:Icons.email_outlined),const SizedBox(height:24),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const VerifyPage())),child:const Text('Enviar código'))]); }

class VerifyPage extends StatelessWidget { const VerifyPage({super.key}); @override Widget build(BuildContext c)=>AuthShell(title:'Verifique seu acesso',subtitle:'Digite o código de 6 dígitos enviado para você.',children:[const Field(label:'Código de verificação',icon:Icons.verified_outlined),const SizedBox(height:10),TextButton(onPressed:(){},child:const Text('Reenviar código')),const SizedBox(height:12),FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>const NewPasswordPage())),child:const Text('Verificar'))]); }

class NewPasswordPage extends StatelessWidget { const NewPasswordPage({super.key}); @override Widget build(BuildContext c)=>AuthShell(title:'Nova senha',subtitle:'Escolha uma senha segura para sua conta.',children:[const Field(label:'Nova senha',icon:Icons.lock_outline,obscure:true),const SizedBox(height:14),const Field(label:'Confirmar senha',icon:Icons.lock_outline,obscure:true),const SizedBox(height:24),FilledButton(onPressed:()=>Navigator.pushAndRemoveUntil(c,MaterialPageRoute(builder:(_)=>const HomePage()),(_)=>false),child:const Text('Salvar nova senha'))]); }

class AuthShell extends StatelessWidget { final String title,subtitle; final List<Widget> children; const AuthShell({super.key,required this.title,required this.subtitle,required this.children}); @override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.all(28),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[const SizedBox(height:24),const Icon(Icons.restaurant_rounded,size:48,color:Color(0xFF0D3B36)),const SizedBox(height:38),Text(title,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w800)),const SizedBox(height:10),Text(subtitle,style:const TextStyle(color:Colors.black54,fontSize:16,height:1.4)),const SizedBox(height:34),...children]))));}
class Field extends StatelessWidget { final String label; final IconData icon; final bool obscure; const Field({super.key,required this.label,required this.icon,this.obscure=false}); @override Widget build(BuildContext c)=>TextField(obscureText:obscure,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(16),borderSide:BorderSide.none))); }

class HomePage extends StatelessWidget { const HomePage({super.key}); @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('RESERVA7',style:TextStyle(fontWeight:FontWeight.w800,letterSpacing:2)),actions:[IconButton(onPressed:(){},icon:const Icon(Icons.notifications_none_rounded))]),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Boa noite',style:TextStyle(color:Colors.black54)),const Text('Onde você quer viver\numa experiência?',style:TextStyle(fontSize:30,fontWeight:FontWeight.w800,height:1.1)),const SizedBox(height:24),TextField(decoration:InputDecoration(hintText:'Restaurante, cozinha ou experiência',prefixIcon:const Icon(Icons.search),filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:BorderSide.none))),const SizedBox(height:30),const Text('Para você',style:TextStyle(fontSize:21,fontWeight:FontWeight.w700)),const SizedBox(height:14),const ExperienceCard(name:'Casa Alba',type:'Mediterrâneo · Salamanca',price:'€€€'),const ExperienceCard(name:'Brasa Madrid',type:'Grelhados · Centro',price:'€€'),const ExperienceCard(name:'Atelier 7',type:'Contemporâneo · Chamberí',price:'€€€')]),bottomNavigationBar:NavigationBar(selectedIndex:0,onDestinationSelected:(_){},destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Início'),NavigationDestination(icon:Icon(Icons.search),label:'Explorar'),NavigationDestination(icon:Icon(Icons.event_outlined),label:'Reservas'),NavigationDestination(icon:Icon(Icons.person_outline),label:'Perfil')]));}}
class ExperienceCard extends StatelessWidget { final String name,type,price; const ExperienceCard({super.key,required this.name,required this.type,required this.price}); @override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:14),padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22)),child:Row(children:[Container(width:72,height:72,decoration:BoxDecoration(color:const Color(0xFFE3EAE5),borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.restaurant_rounded,size:30,color:Color(0xFF0D3B36))),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(name,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:17)),const SizedBox(height:5),Text(type,style:const TextStyle(color:Colors.black54)),const SizedBox(height:6),Text(price,style:const TextStyle(fontWeight:FontWeight.w600))])),const Icon(Icons.chevron_right_rounded)]));}
