import 'package:flutter/material.dart';
import 'main.dart';

void nav(BuildContext c, Widget p) => Navigator.push(c, MaterialPageRoute(builder: (_) => p));
void home(BuildContext c) => Navigator.pushAndRemoveUntil(c, MaterialPageRoute(builder: (_) => const HomePage()), (_) => false);

class SplashPage extends StatefulWidget { const SplashPage({super.key}); @override State<SplashPage> createState()=>_SplashPageState(); }
class _SplashPageState extends State<SplashPage>{
  @override void initState(){super.initState();Future.delayed(const Duration(milliseconds:1500),(){if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const OnboardingPage()));});}
  @override Widget build(BuildContext c)=>Scaffold(backgroundColor:green,body:Center(child:Column(mainAxisSize:MainAxisSize.min,children:[
    Container(width:88,height:88,decoration:BoxDecoration(color:Colors.white12,borderRadius:BorderRadius.circular(28)),child:const Icon(Icons.restaurant_rounded,color:Colors.white,size:44)),
    const SizedBox(height:22),const Text('RESERVA7',style:TextStyle(color:Colors.white,fontSize:30,fontWeight:FontWeight.w900,letterSpacing:5)),const SizedBox(height:8),
    const Text('Reserve. Experience. Enjoy.',style:TextStyle(color:Colors.white60))
  ])));
}

class OnboardingPage extends StatefulWidget{const OnboardingPage({super.key});@override State<OnboardingPage> createState()=>_OnboardingPageState();}
class _OnboardingPageState extends State<OnboardingPage>{
 int page=0; final slides=const[('Descubra lugares especiais','Restaurantes, mesas e experiências selecionadas para você.',Icons.explore_rounded),('Reserve em poucos segundos','Veja horários disponíveis e confirme sua experiência.',Icons.event_available_rounded),('Tudo em um só lugar','Acompanhe reservas, favoritos e novas experiências.',Icons.auto_awesome_rounded)];
 void finish()=>Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const LoginPage()));
 @override Widget build(BuildContext c){final s=slides[page];return Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.fromLTRB(24,18,24,24),child:Column(children:[
  Align(alignment:Alignment.centerRight,child:TextButton(onPressed:finish,child:const Text('Pular'))),
  Expanded(child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[
   Container(height:310,width:double.infinity,decoration:BoxDecoration(gradient:const LinearGradient(colors:[mint,Color(0xFFD0DED8)]),borderRadius:BorderRadius.circular(36)),child:Center(child:Icon(s.$3,size:110,color:green))),
   const SizedBox(height:36),Text(s.$1,textAlign:TextAlign.center,style:const TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:12),Text(s.$2,textAlign:TextAlign.center,style:const TextStyle(fontSize:16,color:Colors.black54,height:1.45))
  ])),
  Row(mainAxisAlignment:MainAxisAlignment.center,children:List.generate(3,(i)=>AnimatedContainer(duration:const Duration(milliseconds:200),margin:const EdgeInsets.all(4),width:i==page?28:8,height:8,decoration:BoxDecoration(color:i==page?green:Colors.black12,borderRadius:BorderRadius.circular(8))))),
  const SizedBox(height:20),Button(label:page<2?'Continuar':'Começar',onTap:(){if(page<2)setState(()=>page++);else finish();})
 ]))));}
}

class LoginPage extends StatefulWidget{const LoginPage({super.key});@override State<LoginPage> createState()=>_LoginPageState();}
class _LoginPageState extends State<LoginPage>{final email=TextEditingController(),password=TextEditingController();bool hidden=true;@override void dispose(){email.dispose();password.dispose();super.dispose();}
 @override Widget build(BuildContext c)=>Auth(title:'Bem-vindo de volta',subtitle:'Entre para continuar sua experiência.',children:[
 Field(email,'E-mail',Icons.email_outlined,keyboard:TextInputType.emailAddress),const SizedBox(height:13),Field(password,'Senha',Icons.lock_outline,obscure:hidden,suffix:IconButton(onPressed:()=>setState(()=>hidden=!hidden),icon:Icon(hidden?Icons.visibility_outlined:Icons.visibility_off_outlined))),
 Align(alignment:Alignment.centerRight,child:TextButton(onPressed:()=>nav(c,const RecoveryPage()),child:const Text('Esqueci minha senha'))),const SizedBox(height:7),Button(label:'Entrar',onTap:()=>nav(c,const LocationPage())),const SizedBox(height:12),Outline(label:'Criar minha conta',onTap:()=>nav(c,const RegisterPage()))
 ]);}

class RegisterPage extends StatefulWidget{const RegisterPage({super.key});@override State<RegisterPage> createState()=>_RegisterPageState();}
class _RegisterPageState extends State<RegisterPage>{final name=TextEditingController(),email=TextEditingController(),phone=TextEditingController(),pass=TextEditingController();bool hidden=true;@override void dispose(){name.dispose();email.dispose();phone.dispose();pass.dispose();super.dispose();}
 @override Widget build(BuildContext c)=>Auth(title:'Crie sua conta',subtitle:'Uma conta simples para guardar suas experiências.',children:[Field(name,'Nome completo',Icons.person_outline),const SizedBox(height:13),Field(email,'E-mail',Icons.email_outlined),const SizedBox(height:13),Field(phone,'Telefone',Icons.phone_outlined,keyboard:TextInputType.phone),const SizedBox(height:13),Field(pass,'Senha',Icons.lock_outline,obscure:hidden,suffix:IconButton(onPressed:()=>setState(()=>hidden=!hidden),icon:Icon(hidden?Icons.visibility_outlined:Icons.visibility_off_outlined))),const SizedBox(height:24),Button(label:'Continuar',onTap:()=>nav(c,const VerifyPage(title:'Confirme seu cadastro',nextNewPassword:false))) ]);}

class RecoveryPage extends StatefulWidget{const RecoveryPage({super.key});@override State<RecoveryPage> createState()=>_RecoveryPageState();}
class _RecoveryPageState extends State<RecoveryPage>{final email=TextEditingController();@override void dispose(){email.dispose();super.dispose();}
 @override Widget build(BuildContext c)=>Auth(title:'Recuperar acesso',subtitle:'Digite seu e-mail e enviaremos um código de verificação.',children:[Field(email,'E-mail',Icons.email_outlined),const SizedBox(height:24),Button(label:'Enviar código',onTap:()=>nav(c,const VerifyPage(title:'Recuperar acesso',nextNewPassword:true))) ]);}

class VerifyPage extends StatefulWidget{final String title;final bool nextNewPassword;const VerifyPage({super.key,required this.title,this.nextNewPassword=true});@override State<VerifyPage> createState()=>_VerifyPageState();}
class _VerifyPageState extends State<VerifyPage>{final code=TextEditingController();@override void dispose(){code.dispose();super.dispose();}
 @override Widget build(BuildContext c)=>Auth(title:widget.title,subtitle:'Digite o código de 6 dígitos enviado para seu e-mail.',children:[Field(code,'Código de verificação',Icons.verified_outlined,keyboard:TextInputType.number,maxLength:6),Center(child:TextButton(onPressed:(){},child:const Text('Reenviar código'))),Button(label:'Verificar',onTap:()=>widget.nextNewPassword?nav(c,const NewPasswordPage()):nav(c,const LocationPage()))]);}

class NewPasswordPage extends StatefulWidget{const NewPasswordPage({super.key});@override State<NewPasswordPage> createState()=>_NewPasswordPageState();}
class _NewPasswordPageState extends State<NewPasswordPage>{final a=TextEditingController(),b=TextEditingController();bool hidden=true;@override void dispose(){a.dispose();b.dispose();super.dispose();}
 @override Widget build(BuildContext c)=>Auth(title:'Nova senha',subtitle:'Crie uma nova senha segura para sua conta.',children:[Field(a,'Nova senha',Icons.lock_outline,obscure:hidden),const SizedBox(height:13),Field(b,'Confirmar senha',Icons.lock_outline,obscure:hidden),const SizedBox(height:24),Button(label:'Salvar nova senha',onTap:()=>nav(c,const LoginPage()))]);}

class LocationPage extends StatelessWidget{const LocationPage({super.key});@override Widget build(BuildContext c)=>ChoicePage(icon:Icons.location_on_rounded,eyebrow:'PERSONALIZE SUA EXPERIÊNCIA',title:'Onde você está?',subtitle:'Usaremos sua localização para mostrar experiências e disponibilidade perto de você.',primary:'Usar minha localização',secondary:'Escolher cidade manualmente',onPrimary:()=>nav(c,const CityPage()),onSecondary:()=>nav(c,const CityPage()));}
class CityPage extends StatelessWidget{const CityPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(backgroundColor:cream,elevation:0),body:ListView(padding:const EdgeInsets.all(24),children:[const Text('Escolha sua cidade',style:TextStyle(fontSize:31,fontWeight:FontWeight.w900)),const SizedBox(height:8),const Text('Experiências disponíveis na região escolhida.',style:TextStyle(color:Colors.black54)),const SizedBox(height:25),CityTile('Madrid','España',Icons.location_city_rounded,()=>home(c)),CityTile('Barcelona','España',Icons.waves_rounded,()=>home(c)),CityTile('São Paulo','Brasil',Icons.apartment_rounded,()=>home(c))]));}

class HomePage extends StatefulWidget{const HomePage({super.key});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{int tab=0;bool onlyOpen=false;final data=const[('Casa Alba','Mediterrâneo','Salamanca','€€€',Icons.restaurant_rounded),('Brasa Madrid','Grelhados','Centro','€€',Icons.local_fire_department_rounded),('Atelier 7','Contemporâneo','Chamberí','€€€',Icons.auto_awesome_rounded),('Luna Wine Bar','Wine & tapas','Malasaña','€€',Icons.wine_bar_rounded)];
 @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(backgroundColor:cream,elevation:0,title:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('RESERVA7',style:TextStyle(fontSize:17,fontWeight:FontWeight.w900,letterSpacing:2)),Text(['Início','Explorar','Reservas','Perfil'][tab],style:const TextStyle(fontSize:11,color:Colors.black45))]),actions:[IconButton(onPressed:()=>nav(c,const NotificationsPage()),icon:const Icon(Icons.notifications_none_rounded))]),body:IndexedStack(index:tab,children:[homeTab(c),exploreTab(c),bookingsTab(c),profileTab(c)]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(v)=>setState(()=>tab=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home_rounded),label:'Início'),NavigationDestination(icon:Icon(Icons.search_outlined),selectedIcon:Icon(Icons.search_rounded),label:'Explorar'),NavigationDestination(icon:Icon(Icons.event_outlined),selectedIcon:Icon(Icons.event_rounded),label:'Reservas'),NavigationDestination(icon:Icon(Icons.person_outline_rounded),selectedIcon:Icon(Icons.person_rounded),label:'Perfil')]);}
 Widget card(BuildContext c,(String,String,String,String,IconData)e)=>PlaceCard(data:e,onTap:()=>nav(c,DetailPage(name:e.$1,type:e.$2,location:e.$3,price:e.$4,icon:e.$5)));
 Widget homeTab(BuildContext c)=>ListView(padding:const EdgeInsets.fromLTRB(20,8,20,30),children:[const Text('Boa noite',style:TextStyle(color:Colors.black45)),const SizedBox(height:4),const Text('Onde você quer viver\numa experiência?',style:TextStyle(fontSize:31,fontWeight:FontWeight.w900,height:1.05)),const SizedBox(height:21),TextField(onTap:()=>setState(()=>tab=1),decoration:const InputDecoration(hintText:'Restaurante, cozinha ou experiência',prefixIcon:Icon(Icons.search_rounded))),const SizedBox(height:24),const Text('Categorias',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:10),SizedBox(height:91,child:ListView(scrollDirection:Axis.horizontal,children:const[Cat(Icons.restaurant_rounded,'Restaurantes'),Cat(Icons.local_fire_department_rounded,'Brasa'),Cat(Icons.wine_bar_rounded,'Wine'),Cat(Icons.cake_rounded,'Celebrar'),Cat(Icons.auto_awesome_rounded,'Experiências')])),const SizedBox(height:18),const HeroBox(),const SizedBox(height:25),const Text('Para você',style:TextStyle(fontSize:21,fontWeight:FontWeight.w800)),const SizedBox(height:12),...data.take(3).map((e)=>card(c,e))]);
 Widget exploreTab(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Explore',style:TextStyle(fontSize:31,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('Encontre o próximo lugar para viver algo especial.',style:TextStyle(color:Colors.black54)),const SizedBox(height:20),const TextField(decoration:InputDecoration(hintText:'Buscar por nome, cozinha...',prefixIcon:Icon(Icons.search_rounded),suffixIcon:Icon(Icons.tune_rounded))),const SizedBox(height:16),Wrap(spacing:8,children:['Todos','Mediterrâneo','Brasa','Wine','Contemporâneo'].map((x)=>FilterChip(label:Text(x),selected:x=='Todos',onSelected:(_){ })).toList()),const SizedBox(height:18),...data.map((e)=>card(c,e))]);
 Widget bookingsTab(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[const Empty(icon:Icons.event_available_rounded),const SizedBox(height:18),const Center(child:Text('Suas reservas aparecerão aqui',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800))),const SizedBox(height:7),const Center(child:Text('Escolha uma experiência e faça sua primeira reserva.',textAlign:TextAlign.center,style:TextStyle(color:Colors.black54))),const SizedBox(height:20),Button(label:'Explorar experiências',onTap:()=>setState(()=>tab=1))]);
 Widget profileTab(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:green,borderRadius:BorderRadius.circular(26)),child:const Row(children:[CircleAvatar(radius:30,backgroundColor:Colors.white24,child:Icon(Icons.person_rounded,color:Colors.white,size:30)),SizedBox(width:14),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Maurício',style:TextStyle(color:Colors.white,fontSize:20,fontWeight:FontWeight.w800)),Text('Perfil e preferências',style:TextStyle(color:Colors.white70))])])),const SizedBox(height:18),ProfileTile('Dados pessoais',Icons.person_outline_rounded,()=>nav(c,const PersonalDataPage())),ProfileTile('Favoritos',Icons.favorite_border_rounded,()=>nav(c,const FavoritesPage())),ProfileTile('Localização',Icons.location_on_outlined,()=>nav(c,const CityPage())),ProfileTile('Notificações',Icons.notifications_none_rounded,()=>nav(c,const NotificationsPage())),ProfileTile('Ajuda e suporte',Icons.help_outline_rounded,()=>nav(c,const SupportPage())),ProfileTile('Termos e privacidade',Icons.shield_outlined,()=>nav(c,const TermsPage())),const SizedBox(height:8),Outline(label:'Sair da conta',onTap:()=>Navigator.pushAndRemoveUntil(c,MaterialPageRoute(builder:(_)=>const LoginPage()),(_)=>false))]);}

class DetailPage extends StatelessWidget{final String name,type,location,price;final IconData icon;const DetailPage({super.key,required this.name,required this.type,required this.location,required this.price,required this.icon});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(backgroundColor:cream,elevation:0,actions:[IconButton(onPressed:()=>nav(c,const FavoritesPage()),icon:const Icon(Icons.favorite_border_rounded))]),body:ListView(padding:const EdgeInsets.all(20),children:[Container(height:255,decoration:BoxDecoration(gradient:const LinearGradient(colors:[green,Color(0xFF2D7568)]),borderRadius:BorderRadius.circular(30)),child:Center(child:Icon(icon,color:Colors.white,size:90))),const SizedBox(height:20),Text(name,style:const TextStyle(fontSize:31,fontWeight:FontWeight.w900)),const SizedBox(height:6),Text(type+' · '+location,style:const TextStyle(color:Colors.black54,fontSize:16)),const SizedBox(height:15),Wrap(spacing:8,children:[InfoChip(Icons.star_rounded,'4.9'),InfoChip(Icons.location_on_outlined,location),InfoChip(Icons.euro_rounded,price)]),const SizedBox(height:24),const Text('Sobre a experiência',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:9),const Text('Uma experiência selecionada pelo Reserva7. Ambiente, gastronomia e atendimento reunidos para uma noite especial.',style:TextStyle(color:Colors.black54,height:1.5)),const SizedBox(height:20),const Text('Informações',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:10),const Text('Aberto hoje · 19:00–00:00\nCancelamento gratuito até 2 horas antes.',style:TextStyle(color:Colors.black54,height:1.5)),const SizedBox(height:28),Button(label:'Ver disponibilidade',onTap:()=>nav(c,BookingPage(place:name))) ]));}

class BookingPage extends StatefulWidget{final String place;const BookingPage({super.key,required this.place});@override State<BookingPage> createState()=>_BookingPageState();}
class _BookingPageState extends State<BookingPage>{int date=0,time=0,people=2;final dates=['Hoje','Amanhã','30 Set','01 Out','02 Out'];final times=['19:00','19:30','20:00','20:30','21:00'];@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Fazer reserva',style:TextStyle(fontWeight:FontWeight.w800)),backgroundColor:cream,elevation:0),body:ListView(padding:const EdgeInsets.all(20),children:[Text(widget.place,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:24),const Text('Escolha a data',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:12),SizedBox(height:70,child:ListView(scrollDirection:Axis.horizontal,children:List.generate(dates.length,(i)=>SelectDate(label:dates[i],selected:date==i,onTap:()=>setState(()=>date=i)))),const SizedBox(height:25),const Text('Número de pessoas',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),Row(children:[IconButton(onPressed:people>1?()=>setState(()=>people--):null,icon:const Icon(Icons.remove_circle_outline)),Text('$people',style:const TextStyle(fontSize:22,fontWeight:FontWeight.w800)),IconButton(onPressed:()=>setState(()=>people++),icon:const Icon(Icons.add_circle_outline))]),const SizedBox(height:16),const Text('Horário disponível',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:10),Wrap(spacing:8,runSpacing:8,children:List.generate(times.length,(i)=>ChoiceChip(label:Text(times[i]),selected:time==i,onSelected:(_)=>setState(()=>time=i)))),const SizedBox(height:30),Button(label:'Continuar',onTap:()=>nav(c,BookingReviewPage(place:widget.place,date:dates[date],time:times[time],people:people))) ]));}

class BookingReviewPage extends StatelessWidget{final String place,date,time;final int people;const BookingReviewPage({super.key,required this.place,required this.date,required this.time,required this.people});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Revisar reserva',style:TextStyle(fontWeight:FontWeight.w800)),backgroundColor:cream,elevation:0),body:ListView(padding:const EdgeInsets.all(20),children:[Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(24)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('SUA RESERVA',style:TextStyle(color:gold,fontSize:11,fontWeight:FontWeight.w900,letterSpacing:2)),const SizedBox(height:14),Text(place,style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900)),const SizedBox(height:16),ReviewRow(Icons.calendar_month_rounded,date),ReviewRow(Icons.schedule_rounded,time),ReviewRow(Icons.people_alt_outlined,'$people pessoas'),ReviewRow(Icons.location_on_outlined,'Madrid') ])),const SizedBox(height:20),const Text('Pagamento',style:TextStyle(fontSize:20,fontWeight:FontWeight.w800)),const SizedBox(height:10),ProfileTile('Cartão terminado em 4242',Icons.credit_card_rounded,(){}),const SizedBox(height:24),Button(label:'Confirmar reserva',onTap:()=>nav(c,ConfirmationPage(place:place,date:date,time:time,people:people))) ]));}

class ConfirmationPage extends StatelessWidget{final String place,date,time;final int people;const ConfirmationPage({super.key,required this.place,required this.date,required this.time,required this.people});@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Container(width:105,height:105,decoration:BoxDecoration(color:mint,borderRadius:BorderRadius.circular(34)),child:const Icon(Icons.check_rounded,size:60,color:green)),const SizedBox(height:28),const Text('Reserva confirmada',style:TextStyle(fontSize:31,fontWeight:FontWeight.w900)),const SizedBox(height:10),Text(place,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w700)),const SizedBox(height:8),Text('$date · $time · $people pessoas',style:const TextStyle(color:Colors.black54)),const SizedBox(height:35),Button(label:'Ir para minhas reservas',onTap:()=>home(c)),const SizedBox(height:8),TextButton(onPressed:()=>home(c),child:const Text('Voltar ao início'))])));}

class NotificationsPage extends StatelessWidget{const NotificationsPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Notificações',style:TextStyle(fontWeight:FontWeight.w800)),backgroundColor:cream,elevation:0),body:ListView(padding:const EdgeInsets.all(20),children:[Notice(Icons.auto_awesome_rounded,'Novas experiências em Madrid','Descubra lugares selecionados perto de você.'),Notice(Icons.event_available_rounded,'Sua próxima reserva','Tenha seus detalhes sempre à mão.') ]));}
class FavoritesPage extends StatelessWidget{const FavoritesPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Favoritos',style:TextStyle(fontWeight:FontWeight.w800)),backgroundColor:cream,elevation:0),body:ListView(padding:const EdgeInsets.all(20),children:[PlaceCard(data:const ('Casa Alba','Mediterrâneo','Salamanca','€€€',Icons.restaurant_rounded),onTap:()=>nav(c,const DetailPage(name:'Casa Alba',type:'Mediterrâneo',location:'Salamanca',price:'€€€',icon:Icons.restaurant_rounded))) ]));}
class PersonalDataPage extends StatefulWidget{const PersonalDataPage({super.key});@override State<PersonalDataPage> createState()=>_PersonalDataPageState();}
class _PersonalDataPageState extends State<PersonalDataPage>{final name=TextEditingController(text:'Maurício');final email=TextEditingController(text:'mauricio@email.com');@override void dispose(){name.dispose();email.dispose();super.dispose();}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Dados pessoais',style:TextStyle(fontWeight:FontWeight.w800)),backgroundColor:cream,elevation:0),body:ListView(padding:const EdgeInsets.all(20),children:[Field(name,'Nome',Icons.person_outline),const SizedBox(height:13),Field(email,'E-mail',Icons.email_outlined),const SizedBox(height:13),const FieldReadOnly(label:'Telefone',value:'+34 672 308 986',icon:Icons.phone_outlined),const SizedBox(height:24),Button(label:'Salvar alterações',onTap:()=>Navigator.pop(c))]));}
class SupportPage extends StatelessWidget{const SupportPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Ajuda e suporte',style:TextStyle(fontWeight:FontWeight.w800)),backgroundColor:cream,elevation:0),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Como podemos ajudar?',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:20),SupportTile('Não consigo fazer uma reserva',Icons.event_busy_rounded),SupportTile('Preciso cancelar uma reserva',Icons.cancel_outlined),SupportTile('Problema com minha conta',Icons.person_off_outlined),SupportTile('Falar com o suporte',Icons.chat_bubble_outline_rounded)]));}
class TermsPage extends StatelessWidget{const TermsPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Termos e privacidade',style:TextStyle(fontWeight:FontWeight.w800)),backgroundColor:cream,elevation:0),body:ListView(padding:const EdgeInsets.all(20),children:[const Text('Termos de uso',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:10),const Text('O Reserva7 conecta clientes a experiências e reservas. As condições de cada estabelecimento podem variar.',style:TextStyle(color:Colors.black54,height:1.5)),const SizedBox(height:25),const Text('Privacidade',style:TextStyle(fontSize:25,fontWeight:FontWeight.w900)),const SizedBox(height:10),const Text('Seus dados devem ser tratados de acordo com a finalidade do serviço, segurança e legislação aplicável.',style:TextStyle(color:Colors.black54,height:1.5))]));}

class Auth extends StatelessWidget{final String title,subtitle;final List<Widget> children;const Auth({super.key,required this.title,required this.subtitle,required this.children});@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:SingleChildScrollView(padding:const EdgeInsets.fromLTRB(24,15,24,30),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[IconButton(alignment:Alignment.centerLeft,onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.arrow_back_rounded)),const SizedBox(height:10),Row(children:[Container(width:42,height:42,decoration:BoxDecoration(color:green,borderRadius:BorderRadius.circular(14)),child:const Icon(Icons.restaurant_rounded,color:Colors.white)),const SizedBox(width:12),const Text('RESERVA7',style:TextStyle(fontWeight:FontWeight.w900,letterSpacing:2))]),const SizedBox(height:42),Text(title,style:const TextStyle(fontSize:31,fontWeight:FontWeight.w900)),const SizedBox(height:10),Text(subtitle,style:const TextStyle(color:Colors.black54,fontSize:16,height:1.4)),const SizedBox(height:30),...children])));}
class Field extends StatelessWidget{final TextEditingController controller;final String label;final IconData icon;final bool obscure;final Widget? suffix;final TextInputType? keyboard;final int? maxLength;const Field(this.controller,this.label,this.icon,{super.key,this.obscure=false,this.suffix,this.keyboard,this.maxLength});@override Widget build(BuildContext c)=>TextField(controller:controller,obscureText:obscure,keyboardType:keyboard,maxLength:maxLength,decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon),suffixIcon:suffix,counterText:maxLength==null?null:''));}
class FieldReadOnly extends StatelessWidget{final String label,value;final IconData icon;const FieldReadOnly({super.key,required this.label,required this.value,required this.icon});@override Widget build(BuildContext c)=>InputDecorator(decoration:InputDecoration(labelText:label,prefixIcon:Icon(icon)),child:Text(value));}
class Button extends StatelessWidget{final String label;final VoidCallback onTap;const Button({super.key,required this.label,required this.onTap});@override Widget build(BuildContext c)=>SizedBox(width:double.infinity,child:FilledButton(onPressed:onTap,style:FilledButton.styleFrom(backgroundColor:green,foregroundColor:Colors.white,padding:const EdgeInsets.symmetric(vertical:17),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18))),child:Text(label,style:const TextStyle(fontWeight:FontWeight.w800))));}
class Outline extends StatelessWidget{final String label;final VoidCallback onTap;const Outline({super.key,required this.label,required this.onTap});@override Widget build(BuildContext c)=>SizedBox(width:double.infinity,child:OutlinedButton(onPressed:onTap,style:OutlinedButton.styleFrom(padding:const EdgeInsets.symmetric(vertical:17),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(18))),child:Text(label,style:const TextStyle(fontWeight:FontWeight.w700))));}
class ChoicePage extends StatelessWidget{final IconData icon;final String eyebrow,title,subtitle,primary,secondary;final VoidCallback onPrimary,onSecondary;const ChoicePage({super.key,required this.icon,required this.eyebrow,required this.title,required this.subtitle,required this.primary,required this.secondary,required this.onPrimary,required this.onSecondary});@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(24),child:Column(children:[const Spacer(),Container(width:120,height:120,decoration:BoxDecoration(color:mint,borderRadius:BorderRadius.all(Radius.circular(38))),child:Icon(icon,size:60,color:green)),const SizedBox(height:32),Text(eyebrow,style:const TextStyle(color:gold,fontSize:11,fontWeight:FontWeight.w900,letterSpacing:2)),const SizedBox(height:10),Text(title,textAlign:TextAlign.center,style:const TextStyle(fontSize:32,fontWeight:FontWeight.w900)),const SizedBox(height:14),Text(subtitle,textAlign:TextAlign.center,style:const TextStyle(color:Colors.black54,fontSize:16,height:1.45)),const Spacer(),Button(label:primary,onTap:onPrimary),TextButton(onPressed:onSecondary,child:Text(secondary))])));}
class CityTile extends StatelessWidget{final String city,country;final IconData icon;final VoidCallback onTap;const CityTile(this.city,this.country,this.icon,this.onTap,{super.key});@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:11),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20)),child:ListTile(contentPadding:const EdgeInsets.symmetric(horizontal:18,vertical:7),leading:Container(width:48,height:48,decoration:BoxDecoration(color:mint,borderRadius:BorderRadius.circular(14)),child:Icon(icon,color:green)),title:Text(city,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(country),trailing:const Icon(Icons.chevron_right_rounded),onTap:onTap));}
class Cat extends StatelessWidget{final IconData icon;final String label;const Cat(this.icon,this.label,{super.key});@override Widget build(BuildContext c)=>Container(width:82,margin:const EdgeInsets.only(right:10),child:Column(children:[Container(width:58,height:58,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:Icon(icon,color:green)),const SizedBox(height:7),Text(label,textAlign:TextAlign.center,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700))]));}
class HeroBox extends StatelessWidget{const HeroBox({super.key});@override Widget build(BuildContext c)=>Container(height:190,padding:const EdgeInsets.all(22),decoration:BoxDecoration(color:green,borderRadius:BorderRadius.circular(28)),child:const Stack(children:[Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('EXPERIÊNCIA DA SEMANA',style:TextStyle(color:gold,fontSize:10,fontWeight:FontWeight.w900,letterSpacing:2)),Spacer(),Text('Uma mesa\nque vale a noite.',style:TextStyle(color:Colors.white,fontSize:27,fontWeight:FontWeight.w900,height:1.02)),SizedBox(height:8),Text('Lugares selecionados em Madrid.',style:TextStyle(color:Colors.white70))]),Positioned(right:4,bottom:18,child:Icon(Icons.restaurant_rounded,color:Colors.white24,size:78))]));}
class PlaceCard extends StatelessWidget{final (String,String,String,String,IconData) data;final VoidCallback onTap;const PlaceCard({super.key,required this.data,required this.onTap});@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:12),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(23)),child:InkWell(borderRadius:BorderRadius.circular(23),onTap:onTap,child:Padding(padding:const EdgeInsets.all(13),child:Row(children:[Container(width:82,height:82,decoration:BoxDecoration(color:mint,borderRadius:BorderRadius.circular(17)),child:Icon(data.$5,size:32,color:green)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(data.$1,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w800)),const SizedBox(height:4),Text(data.$2+' · '+data.$3,style:const TextStyle(color:Colors.black54)),const SizedBox(height:7),Text(data.$4,style:const TextStyle(fontWeight:FontWeight.w800))])),const Icon(Icons.chevron_right_rounded,color:Colors.black45)]))));}
class InfoChip extends StatelessWidget{final IconData icon;final String text;const InfoChip(this.icon,this.text,{super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:11,vertical:9),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(14)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(icon,size:15,color:green),const SizedBox(width:5),Text(text,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:12))]));}
class SelectDate extends StatelessWidget{final String label;final bool selected;final VoidCallback onTap;const SelectDate({super.key,required this.label,required this.selected,required this.onTap});@override Widget build(BuildContext c)=>GestureDetector(onTap:onTap,child:Container(width:72,margin:const EdgeInsets.only(right:9),decoration:BoxDecoration(color:selected?green:Colors.white,borderRadius:BorderRadius.circular(18)),alignment:Alignment.center,child:Text(label,style:TextStyle(color:selected?Colors.white:Colors.black,fontWeight:FontWeight.w800,fontSize:12))));}
class ReviewRow extends StatelessWidget{final IconData icon;final String text;const ReviewRow(this.icon,this.text,{super.key});@override Widget build(BuildContext c)=>Padding(padding:const EdgeInsets.only(bottom:12),child:Row(children:[Icon(icon,size:19,color:green),const SizedBox(width:10),Text(text,style:const TextStyle(fontWeight:FontWeight.w600))]));}
class Notice extends StatelessWidget{final IconData icon;final String title,text;const Notice(this.icon,this.title,this.text,{super.key});@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(19)),child:Row(children:[Container(width:45,height:45,decoration:BoxDecoration(color:mint,borderRadius:BorderRadius.circular(14)),child:Icon(icon,color:green)),const SizedBox(width:13),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w800)),const SizedBox(height:4),Text(text,style:const TextStyle(color:Colors.black54))]))]));}
class ProfileTile extends StatelessWidget{final String title;final IconData icon;final VoidCallback onTap;const ProfileTile(this.title,this.icon,this.onTap,{super.key});@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:ListTile(leading:Icon(icon,color:green),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),trailing:const Icon(Icons.chevron_right_rounded),onTap:onTap));}
class SupportTile extends StatelessWidget{final String title;final IconData icon;const SupportTile(this.title,this.icon,{super.key});@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:ListTile(leading:Icon(icon,color:green),title:Text(title,style:const TextStyle(fontWeight:FontWeight.w700)),trailing:const Icon(Icons.chevron_right_rounded)));} 
class Empty extends StatelessWidget{final IconData icon;const Empty({super.key,required this.icon});@override Widget build(BuildContext c)=>Container(height:190,decoration:BoxDecoration(color:mint,borderRadius:BorderRadius.circular(30)),child:Center(child:Icon(icon,size:80,color:green)));}
